### ISSUE TITLE
[Feature] Videoquality and Framerate?

### ISSUE THREAD

**Issue by Unkn0wnCreator** [shawnchin/jitsi-url-generator#3]
Is it possible to add video quality and framerate options?

like 4K 60fps as an extreme example or pin the quality to 1080p 60fps so that i could be sure that everyone will see the same quality

and Stereo sound

**Comment by shawnchin** [comment]
I suppose that is technically possible since `videoQuality` and `desktopSharingFrameRate` are [whitelisted](https://github.com/jitsi/jitsi-meet/blob/master/react/features/base/config/configWhitelist.ts). But frankly I'm hesitant to add it because https://shawnchin.github.io/jitsi-url-generator/ is meant as an "educational" page that shows how jitsi url params can be constructed, but also double as simple UI that standard users could use as a launch point.

Params like videoQuality and desktopSharingFrameRate is something I'd consider as power user options, which does not fit into my mental model of what that page does.

Of course, you are more than welcome to fork the project to change or add options to meet your use case.

> so that i could be sure that everyone will see the same quality

For something that affects all your users, you're better off changing defaults in config.js of your own deployment. Configs overridden via URL params would only affect the local client, so I'm not sure how adding more options to jitsi-url-generator is going to help you in this case.

**Comment by Unkn0wnCreator** [comment]
Thank you for the Response, i will look into it.
